const productsArray = [
    {
        id: 1,
        name: 'iphone 12 Pro',
        description: 'This is iPhone 12 Pro',
        type: 'phone',
        capacity: 64,
        price: 500,
        image: '/images/1.jpg',
    },
    {
        id: 2,
        name: 'iphone 13 Pro Max',
        description: 'This is iPhone 13 Pro Max',
        type: 'phone',
        capacity: 128,
        price: 900,
        image: '/images/2.jpg',
    },
    {
        id: 3,
        name: 'iphone 11',
        description: 'This is iPhone 11',
        type: 'phone',
        capacity: 128,
        price: 700,
        image: '/images/3.jpg',
    },
    {
        id: 4,
        name: 'iphone 11',
        description: 'This is iPhone 11',
        type: 'phone',
        capacity: 64,
        price: 300,
        image: '/images/4.jpg',
    },
    {
        id: 5,
        name: 'iphone 13',
        description: 'This is iPhone 13',
        type: 'phone',
        capacity: 128,
        price: 900,
        image: '/images/5.jpg',
    },
    {
        id: 6,
        name: 'iphone 12 Pro Max',
        description: 'This is iPhone 12 Pro Max',
        type: 'phone',
        capacity: 128,
        price: 849,
        image: '/images/6.jpg',
    },
]

export default productsArray
